### ISSUE TITLE
Left Panel - Home button doesn't return the Main Panel to Home content

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-template-vue-f7-split-panel#10]
When cycling through the buttons on the Left Panel - Home, About, Services etc...

Then click on the Home button to return to the Home page.

The Main Panel doesn't load the Home page content and just stays at the last page loaded (either the About content or Services content).

**Comment by macdonst** [comment]
I can reproduce this as well.

**Comment by hermwong** [comment]
Detailed steps to reproduce:

1. load up the app and serve it locally
1. you should see the Home content in the Main panel
1. click on the hamburger menu
1. click on the About button
1. the Main panel will display the About content
1. click on the hamburger menu
1. click on the Home button
1. the Main panel **does not** display the Home content

The above use case can also be reproduced by using Services button instead of the About button or if you just randomly click through About, Services and Home button.

**Comment by hermwong** [comment]
Looks like this is fixed with this commit: a81957c22f6380028b2214cd39360a4a060f27d6

@macdonst we must have created the template for the voice-memo-pwa right before @devgeeks made this change.

**Comment by maverickmishra** [comment]
The issue in the phonegap-app-voice-memos is fixed here : https://github.com/phonegap/phonegap-app-voice-memos/commit/c401399fc00ed57d9945471abac2f6a76c52b736

**Comment by macdonst** [comment]
@hermwong yeah, I created it off of npm which doesn't have the change.
