### ISSUE TITLE
Move index.html to ./src

### ISSUE THREAD

**Issue by devgeeks** [phonegap/phonegap-template-vue-f7-split-panel#5]
To avoid confusion, we should move the index.html file that is used to build the final index.html from the root of the project to the `src` folder. This file _is_ a src file in that it is the one that can be edited, then is used to generate the one in the `www` folder for use in Cordova.

**Comment by florianwalter** [comment]
Was this change undone on purpose? (https://github.com/phonegap/phonegap-template-vue-f7-split-panel/commit/8b025bcea1c47bafae4556b1a4d1030e25dd5fd5#diff-d43cc70836893bbbf5ebb598b38ddf42)
